### ISSUE TITLE
Hello, thank you for sharing. I have been using the EFI you provided. It works perfectly when using one CPU, but it does not work with dual CPUs.

### ISSUE THREAD

**Issue by neffoor725** [HJebbour/HP-Z640-Hackintosh#1]
It suddenly shuts down and reboots to the message, "Your computer restarted because of a problem." Additionally, every time I click to sleep, it also reboots with that message.

My hardware configuration is:

Dual Intel Xeon E5-2630 v4 CPUs
HP RX460 2GB GPU
Toshiba 960GB SSD
4x16GB Samsung DDR4 2400MHz RAM, only placed in the motherboard

**Comment by neffoor725** [comment]
Same in Monterey and Sonoma

**Comment by HJebbour** [comment]
I don't have a dual CPU system to test, but here's what you can try and let me know if it worked:
- Add this kext: https://github.com/acidanthera/CpuTscSync
- Make sure you used the correct Cpuid1Data for Broadwell-E
- Try with Sleep enabled and disabled, dual system are know to have a broken Sleep/Wake.

**Comment by neffoor725** [comment]
Thank you. I have added CpuTscSync. kext and AppleMCEReporterDisabler.kext. It seems only add the 2 kextscan work properly. 

Like you said, still can't restore from sleep.  When  wake it up, it  restarts and show "Your computer restarted because of a problem.".

**Comment by neffoor725** [comment]
I have another question,  Memory Modules Misconfigured like the  screenshot. Is yours show correctly? 

I find manually fixing methed in youtube , and it works. Should I manually fix it ? https://www.youtube.com/watch?v=aV2kznYRV2Q
<img width="537" alt="Screenshot 2024-07-10 at 13 27 46" src="https://github.com/HJebbour/HP-Z640-Hackintosh/assets/161777882/d280e818-50fd-4dee-8e2c-f8318b23c86a">

**Comment by HJebbour** [comment]
> Thank you. I have added CpuTscSync. kext and AppleMCEReporterDisabler.kext. It seems only add the 2 kextscan work properly.

I forgot about AppleMCEReporterDisabler.kext, it is required if you have a dual CPU system, could try without CpuTscSync.kext? and check stability and performance?

> I have another question, Memory Modules Misconfigured like the screenshot. Is yours show correctly?

I think this issue was fixed by RestrictEvent.kext but I will check on my Z640 later today and let you know.

I will add the required kexts for Z840 and dual CPU Z640 in the next update once you update me on CpuTscSync.kext requirement.

**Comment by neffoor725** [comment]
Hello, it seems  ok when only using AppleMCEReporterDisabler.kext , without CpuTscSync. kext.  But it still can't restore from sleep.  
![Screenshot 2024-07-10 at 19 04 45](https://github.com/HJebbour/HP-Z640-Hackintosh/assets/161777882/2e3fd0d2-83e5-4b3e-b999-4655bba1b5ac)

**Comment by HJebbour** [comment]
> I have another question, Memory Modules Misconfigured like the screenshot. Is yours show correctly?

I just check my system and I have the same outcome, this is normal behavior if you don't receive a notification about it.

> Hello, it seems ok when only using AppleMCEReporterDisabler.kext , without CpuTscSync. kext. But it still can't restore from sleep.

Great, I will add it later to my repo, as of sleep issue that's common for dual CPU systems as I told, so you have to live without sleep.
